# Enhanced OMOAI Configuration with New Output Options
# This configuration demonstrates the new plugin-based output system

paths:
  chunkformer_dir: ./src/chunkformer
  chunkformer_checkpoint: ./models/chunkformer/chunkformer-large-vie
  out_dir: ./data/output

logging:
  level: INFO
  enable_console: true
  enable_file: true
  log_file: "@logs/api_server.jsonl"
  # Optional human-readable text log alongside JSONL
  enable_text_file: true
  text_log_file: "@logs/api_server.log"
  max_file_size: 10485760  # 10 MB
  backup_count: 5
  # Advanced Loguru options (optional)
  rotation: "10 MB"
  retention: "14 days"
  compression: "gz"
  enqueue: true
  debug_mode: false
  quiet_mode: false

asr:
  total_batch_duration_s: 3600 # 1 hour max (increased)
  chunk_size: 64
  left_context_size: 128
  right_context_size: 128
  device: auto
  autocast_dtype: fp16
  # Memory management for long audio
  max_audio_duration_hours: 2 # Hard limit: 2 hours max

llm:
  model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
  quantization: auto
  max_model_len: 12000
  gpu_memory_utilization: 0.70
  max_num_seqs: 1
  max_num_batched_tokens: 512
  trust_remote_code: true

punctuation:
  llm:
    model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
    quantization: auto
    max_model_len: 12000
    gpu_memory_utilization: 0.70
    max_num_seqs: 1
    max_num_batched_tokens: 512
    trust_remote_code: true
  preserve_original_words: false
  auto_switch_ratio: 0.98
  auto_margin_tokens: 128
  # New behavior controls
  enable_paragraphs: true
  join_separator: " "
  paragraph_gap_seconds: 3.0
  system_prompt: |
    <instruction>
    Bạn là một chuyên gia biên tập tiếng Việt. Nhiệm vụ của bạn là sửa lỗi một cách tỉ mỉ cho văn bản đầu vào về ngữ pháp, chính tả, dấu câu và cách viết hoa.
    - Sửa tất cả các lỗi ngữ pháp và lỗi gõ máy (ví dụ: 'lai trim' -> 'livestream').
    - Chuyển các từ nước ngoài được phiên âm sang tiếng Việt về cách viết gốc của chúng (ví dụ: 'phây búc' -> 'Facebook').
    - Thêm tất cả các dấu câu cần thiết, bao gồm dấu phẩy, dấu chấm, dấu hỏi, v.v.
    - Sửa lỗi viết hoa cho đầu câu và danh từ riêng (ví dụ: 'hà nội' -> 'Hà Nội').
    - Đảm bảo giữ nguyên hoàn toàn từ ngữ, trật tự từ và ý nghĩa gốc ở những phần đã đúng ngữ pháp.
    - Đầu ra của bạn phải là một khối văn bản đã được sửa, liền mạch và không có gì khác.
    </instruction>
    <example>
    <input>xin chào thế giới đây là một ví dụ về khôi phục dấu câu</input>
    <output>Xin chào thế giới, đây là một ví dụ về khôi phục dấu câu.</output>
    </example>
    <example>
    <input>bạn tên là gì tôi tên là nam</input>
    <output>Bạn tên là gì? Tôi tên là Nam.</output>
    </example>
    <example>
    <input>tôi đang xem một buổi lai trim trên phây búc về trí tuệ nhân tạo ai</input>
    <output>Tôi đang xem một buổi livestream trên Facebook về trí tuệ nhân tạo AI.</output>
    </example>
    <example>
    <input>hôm qua tại hà nội thủ tướng đã nói chúng ta cần phải nỗ lực hơn nữa để phát triển kinh tế</input>
    <output>Hôm qua tại Hà Nội, Thủ tướng đã nói: "Chúng ta cần phải nỗ lực hơn nữa để phát triển kinh tế."</output>
    </example>
    <policy>
    QUY TẮC TUYỆT ĐỐI: Giữ nguyên 100% từ ngữ, cấu trúc câu và ý nghĩa gốc. Chỉ can thiệp để sửa các lỗi rõ ràng về ngữ pháp, chính tả, dấu câu và viết hoa. NGHIÊM CẤM viết lại câu, thay thế từ đồng nghĩa hoặc thay đổi văn phong của tác giả.
    </policy>
  user_prompt: "<input>{{TEXT_TO_CORRECT}}</input>"
  sampling:
    temperature: 0.0

summarization:
  llm:
    model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
    quantization: auto
    max_model_len: 12000
    gpu_memory_utilization: 0.70
    max_num_seqs: 1
    max_num_batched_tokens: 512
    trust_remote_code: true
  map_reduce: false
  auto_switch_ratio: 0.98
  auto_margin_tokens: 256
  system_prompt: |
    <instruction>
    Bạn là một chuyên gia phân tích nội dung. Nhiệm vụ của bạn là tạo một bản tóm tắt có cấu trúc, súc tích từ văn bản tiếng Việt được cung cấp.
    - Toàn bộ đầu ra phải bằng tiếng Việt.
    - Tạo một tiêu đề ngắn gọn, phù hợp.
    - Viết một đoạn tóm tắt ngắn (2-4 câu) nêu bật các điểm chính.
    - Liệt kê các ý chính quan trọng nhất dưới dạng danh sách gạch đầu dòng.
    - Đầu ra của bạn phải tuân theo định dạng được chỉ định và không có gì khác.

    Định dạng đầu ra BẮT BUỘC là:
    Tiêu đề: [Tiêu đề bạn tạo bằng tiếng Việt]
    Tóm tắt: [Tóm tắt bạn tạo bằng tiếng Việt]
    Điểm chính:
    - [Điểm chính 1]
    - [Điểm chính 2]
    - [...]
    </instruction>
    <example>
    <input>hôm nay trời đẹp tôi đi dạo công viên và gặp một người bạn cũ chúng tôi đã ngồi uống cà phê và nói chuyện về những kỷ niệm xưa</input>
    <output>
    Tiêu đề: Cuộc gặp gỡ trong công viên
    Tóm tắt: Tác giả tình cờ gặp lại một người bạn cũ khi đi dạo trong công viên. Cả hai đã cùng nhau uống cà phê và ôn lại những kỷ niệm xưa.
    Điểm chính:
    - Tác giả đi dạo công viên và tình cờ gặp lại bạn cũ.
    - Cả hai đã uống cà phê và trò chuyện về kỷ niệm.
    </output>
    </example>
    <example>
    <input>giá cổ phiếu của công ty công nghệ xyz đã tăng 15% trong phiên giao dịch hôm nay sau khi họ công bố báo cáo tài chính quý 3 với lợi nhuận vượt kỳ vọng của giới phân tích công ty cho biết sự tăng trưởng này đến từ mảng kinh doanh đám mây và trí tuệ nhân tạo</input>
    <output>
    Tiêu đề: Cổ Phiếu Công Ty XYZ Tăng Mạnh Sau Báo Cáo Tài Chính
    Tóm tắt: Công ty công nghệ XYZ chứng kiến giá cổ phiếu tăng vọt 15% nhờ báo cáo tài chính quý 3 có lợi nhuận cao hơn dự báo. Động lực tăng trưởng chính được xác định là từ mảng kinh doanh đám mây và trí tuệ nhân tạo.
    Điểm chính:
    - Giá cổ phiếu công ty XYZ tăng 15% trong một ngày.
    - Nguyên nhân là do báo cáo tài chính quý 3 vượt kỳ vọng.
    - Mảng đám mây và trí tuệ nhân tạo là động lực tăng trưởng chính.
    </output>
    </example>
    <example>
    <input>việt nam vừa phóng thành công vệ tinh nano dragon lên quỹ đạo bằng tên lửa epsilon 5 của nhật bản vệ tinh này có nhiệm vụ giám sát hoạt động tàu thuyền và tìm kiếm cứu nạn trên biển</input>
    <output>
    Tiêu đề: Việt Nam Phóng Thành Công Vệ Tinh NanoDragon
    Tóm tắt: Vệ tinh NanoDragon của Việt Nam đã được phóng thành công lên quỹ đạo từ Nhật Bản bằng tên lửa Epsilon 5. Vệ tinh sẽ thực hiện nhiệm vụ quan trọng là giám sát tàu thuyền và hỗ trợ các hoạt động tìm kiếm cứu nạn trên biển.
    Điểm chính:
    - Vệ tinh NanoDragon của Việt Nam đã được phóng thành công.
    - Vụ phóng được thực hiện tại Nhật Bản.
    - Phương tiện phóng là tên lửa Epsilon 5.
    - Nhiệm vụ của vệ tinh là giám sát hàng hải và hỗ trợ tìm kiếm cứu nạn.
    </output>
    </example>
    <policy>
    QUY TẮC TUYỆT ĐỐI: Đầu ra PHẢI bằng tiếng Việt.
    QUY TẮC TUYỆT ĐỐI: KHÔNG thêm thông tin không có trong văn bản gốc.
    QUY TẮC TUYỆT ĐỐI: KHÔNG bao gồm ý kiến hoặc diễn giải cá nhân.
    </policy>
  user_prompt: "<input>{{TEXT_TO_SUMMARIZE}}</input>"
  sampling:
    temperature: 0.7

output:
  # Legacy fields (maintained for backward compatibility)
  write_separate_files: true
  transcript_file: "transcript.txt" # Legacy - maps to transcript.file_punct
  summary_file: "summary.txt" # Legacy - maps to summary.file
  wrap_width: 0 # Legacy - maps to transcript.wrap_width

  # New structured configuration
  formats: ["json", "text", "srt", "vtt", "md"] # All available formats

  # Transcript output configuration
  transcript:
    include_raw: true # Include raw transcript in outputs
    include_punct: true # Include punctuated transcript in outputs
    include_segments: true # Include timestamped segments in outputs
    timestamps: "clock" # Format: "none", "s", "ms", "clock"
    wrap_width: 100 # Text wrapping width (0 = no wrapping)

    # Filename configuration
    file_raw: "transcript.raw.txt"
    file_punct: "transcript.punct.txt"
    file_srt: "transcript.srt"
    file_vtt: "transcript.vtt"
    file_segments: "segments.json"

  # Summary output configuration
  summary:
    mode: "both" # "bullets", "abstract", "both", "none"
    bullets_max: 7 # Maximum number of bullet points
    abstract_max_chars: 1000 # Maximum abstract length
    language: "vi" # Summary language
    file: "summary.md" # Summary output filename

  # Final output filename
  final_json: "final.json"

  # API-related output controls (new)
  # save_on_api: if true, the pipeline API will also persist final JSON to disk
  # default is false to avoid implicit persistence from API calls
  save_on_api: true

  # when save_on_api is true, which files to write (final_json, segments, transcripts)
  save_formats_on_api:
    - final_json
    - segments

  # directory to save API outputs (overrides paths.out_dir when set)
  api_output_dir: "./data/output/api"

api:
  host: "0.0.0.0"
  port: 8000
  max_body_size_mb: 200 # Increased for longer audio files
  request_timeout_seconds: 1800 # 30 minutes to match ASR batch duration
  temp_dir: "/tmp"
  cleanup_temp_files: true
  enable_progress_output: true
  # service_mode removed; script-based pipeline is always used
  health_check_dependencies:
    - ffmpeg
    - config_file
