# Enhanced OMOAI Configuration with New Output Options
# This configuration demonstrates the new plugin-based output system

paths:
  chunkformer_dir: ./src/omoai/chunkformer
  chunkformer_checkpoint: ./chunkformer-large-vie
  out_dir: data/output

asr:
  total_batch_duration_s: 1800
  chunk_size: 64
  left_context_size: 128
  right_context_size: 128
  device: auto
  autocast_dtype: fp16

llm:
  model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
  quantization: auto
  max_model_len: 50000
  gpu_memory_utilization: 0.90
  max_num_seqs: 2
  max_num_batched_tokens: 512
  trust_remote_code: true

punctuation:
  llm:
    model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
    quantization: auto
    max_model_len: 50000
    gpu_memory_utilization: 0.90
    max_num_seqs: 2
    max_num_batched_tokens: 512
    trust_remote_code: true
  preserve_original_words: true
  auto_switch_ratio: 0.98
  auto_margin_tokens: 128
  adopt_case: true
  enable_paragraphs: true
  join_separator: " "
  paragraph_gap_seconds: 3.0
  system_prompt: |
    <instruction>
    You are a Vietnamese text punctuation engine. Your task is to add proper punctuation and capitalization to the input text.
    - Preserve the original word order and meaning
    - Add appropriate punctuation marks (., !, ?, :, ;, etc.)
    - Capitalize the first letter of sentences and proper nouns
    - Use paragraph breaks for natural speech pauses
    - Maintain the original language style and tone
    </instruction>
    <example>
    <input>toi dang xem mot buoi lai trim tren phay buc ve tri tue nhan tao ai</input>
    <output>Tôi đang xem một buổi livestream trên Facebook về trí tuệ nhân tạo AI.</output>
    </example>
  sampling:
    temperature: 0.0

summarization:
  llm:
    model_id: cpatonn/Qwen3-4B-Instruct-2507-AWQ-4bit
    quantization: auto
    max_model_len: 50000
    gpu_memory_utilization: 0.90
    max_num_seqs: 2
    max_num_batched_tokens: 512
    trust_remote_code: true
  map_reduce: false
  auto_switch_ratio: 0.98
  auto_margin_tokens: 256
  system_prompt: |
    <instruction>
    You are a Vietnamese text analysis engine. Your task is to generate a summary of the input text and format it as a single, valid JSON object.
    - The JSON object must contain exactly two keys: "bullets" and "abstract".
    - The "bullets" value must be an array of 3 to 7 concise Vietnamese strings (max 20 words each).
    - The "abstract" value must be a string containing a 2-3 sentence summary in Vietnamese.
    - Do not output any text before or after the JSON object.
    - The summary must be based exclusively on the provided text.
    </instruction>
    <example>
    <input>Hệ thống nhận dạng giọng nói đã trở thành một công nghệ phổ biến. Nó được sử dụng trong nhiều ứng dụng từ trợ lý ảo đến điều khiển bằng giọng nói trong xe hơi. Công nghệ này giúp tăng cường sự tiện lợi và hiệu quả.</input>
    <output>
    {
      "bullets": [
        "Hệ thống nhận dạng giọng nói là công nghệ phổ-biến.",
        "Nó có nhiều ứng dụng như trợ-lý ảo và điều-khiển xe hơi.",
        "Công nghệ này giúp tăng sự tiện lợi và hiệu quả."
      ],
      "abstract": "Hệ thống nhận dạng giọng nói là một công nghệ phổ biến được sử dụng trong nhiều ứng dụng, từ trợ lý ảo đến điều khiển bằng giọng nói trong xe hơi. Công nghệ này giúp tăng cường sự tiện lợi và hiệu quả cho người dùng."
    }
    </output>
    </example>
  sampling:
    temperature: 0.7

# NEW: Enhanced Output Configuration
# Legacy fields (maintained for backward compatibility)
write_separate_files: true
transcript_file: "transcript.txt" # Legacy - maps to transcript.file_punct
summary_file: "summary.txt" # Legacy - maps to summary.file
wrap_width: 0 # Legacy - maps to transcript.wrap_width

# New structured configuration
formats: ["json", "text", "srt", "vtt", "md"] # All available formats

# Transcript output configuration
transcript:
  include_raw: true # Include raw transcript in outputs
  include_punct: true # Include punctuated transcript in outputs
  include_segments: true # Include timestamped segments in outputs
  timestamps: "clock" # Format: "none", "s", "ms", "clock"
  wrap_width: 100 # Text wrapping width (0 = no wrapping)

  # Filename configuration
  file_raw: "transcript.raw.txt"
  file_punct: "transcript.punct.txt"
  file_srt: "transcript.srt"
  file_vtt: "transcript.vtt"
  file_segments: "segments.json"

# Summary output configuration
summary:
  mode: "both" # "bullets", "abstract", "both", "none"
  bullets_max: 7 # Maximum number of bullet points
  abstract_max_chars: 1000 # Maximum abstract length
  language: "vi" # Summary language
  file: "summary.md" # Summary output filename

# Final output filename
final_json: "final.json"

api:
  host: "0.0.0.0"
  port: 8000
  max_body_size_mb: 100
  request_timeout_seconds: 300
  temp_dir: "/tmp"
  cleanup_temp_files: true
  enable_progress_output: true
  health_check_dependencies:
    - ffmpeg
    - config_file
    - asr_script
    - postprocess_script
